services:
  server:
    build:
      context: .
      target: final
    ports:
      - 8080:8080
    develop:
      watch:
        - action: rebuild
          path: ./cmd
          interval: 10s
        - action: rebuild
          path: ./pkg
          interval: 10s
    depends_on:
       db:
         condition: service_healthy
    configs:
      - source: api-config
        target: /etc/todoapp/config.yaml
    environment:
      - GIN_MODE=release
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health-check"]
      interval: 30s
      timeout: 5s
      retries: 5
  db:
     image: postgres
     restart: always
     user: postgres
     secrets:
       - db-password
     volumes:
       - db-data-todo:/var/lib/postgresql/data
     environment:
       - POSTGRES_DB=todoapp
       - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
     expose:
       - 5432
     healthcheck:
       test: [ "CMD", "pg_isready" ]
       interval: 10s
       timeout: 5s
       retries: 5
volumes:
   db-data-todo:
secrets:
   db-password:
     file: db/password.txt
configs:
  api-config:
    file: ./config.yaml